name: Deploy Release
run-name: Deploy release ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version release'
        required: true
        default: '11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}