name: Deploy Release
run-name: Deploy release ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version release'
        required: true
        default: '80'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - name: Git config
        run: |
          git config --global user.name "Vladislav Serov"
          git config --global user.email "serov.vladsilaw@yandex.ru"
          git checkout release/${{ github.event.inputs.release_version }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: docker stop $(docker ps -aq) |
            docker pull cr.yandex/crpuv35ridrbq7gl8980/app:${{ github.event.inputs.release_version }}_latest |
            docker run -d -p 3000:3000 cr.yandex/crpuv35ridrbq7gl8980/app:${{ github.event.inputs.release_version }}_latest