name: Linting, testing
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        script: ['npm run lint', 'npm run test']

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: Run script
        run: ${{ matrix.script }}